FROM python:3.11-slim

WORKDIR /app

COPY requirements_simulator.txt .
RUN pip install --no-cache-dir -r requirements_simulator.txt

COPY extreme_simulator.py .

CMD ["python", "extreme_simulator.py"]
